import { useState } from 'react';
import { business } from '../data/config';
import { ArrowLeft, ShoppingBag, Trash2, Info } from 'lucide-react';
import type { OrderItem, PaymentPreference } from '../types/menu';
import { buildWhatsAppMessage, buildOrderWhatsAppUrl, money, orderSubtotal, orderTotal } from '../utils/whatsapp';
import { Dialog, Quantity, WhatsAppIcon } from './UI';
export default function Cart({items,onChange,onClose}:{items:OrderItem[];onChange:(items:OrderItem[])=>void;onClose:()=>void}) {
 const [name,setName]=useState(''); const [note,setNote]=useState(''); const [review,setReview]=useState(false);
 const [payment,setPayment]=useState<PaymentPreference | null>(null); const total=orderTotal(items); const subtotal=orderSubtotal(items);
 return <Dialog title={review?'Revise seu pedido':'Seu pedido'} onClose={onClose}>
 {items.length===0?<div className="empty"><ShoppingBag size={40}/><h3>O pedido começa no cardápio</h3><p className="muted">Escolha o que deseja e adicione por aqui.</p><button className="button primary" onClick={onClose}>Ver cardápio</button></div>:<>
 <div className="cart-items">{items.map(item=><article className="cart-item" key={item.id}><div className="cart-item-heading"><h3>{item.name}{item.variant?' · '+item.variant:''}</h3>{!review&&<button className="icon-button" aria-label={'Remover '+item.name} onClick={()=>onChange(items.filter(i=>i.id!==item.id))}><Trash2 size={18}/></button>}</div>{item.flavors&&<p>{item.flavors.join(' / ')}</p>}{item.border&&<p>Borda: {item.border} <span className="muted">({item.borderPrice==null?"valor a confirmar":money(item.borderPrice)+" por unidade; incluída no valor quando confirmado"})</span></p>}<div className="cart-item-bottom">{review?<span>{item.quantity}x</span>:<Quantity label={item.name} value={item.quantity} onChange={quantity=>onChange(items.map(i=>i.id===item.id?{...i,quantity}:i))}/>}<span>{item.unitPrice===null?'Valor: a confirmar pelo WhatsApp':money(item.unitPrice*item.quantity)}</span></div>{item.unitPrice!==null&&<p className="small muted">Valor confirmado: {money(item.unitPrice)} por unidade</p>}</article>)}</div>
 <dl className="price-breakdown cart-breakdown"><div><dt>Subtotal dos produtos</dt><dd>{subtotal===null?"A confirmar":money(subtotal)}</dd></div><div><dt>Entrega</dt><dd>{money(business.deliveryFee)}</dd></div></dl><div className="cart-total"><span>Total</span><strong>{total===null?'Valor a confirmar pelo WhatsApp':money(total)}</strong></div>
 {!review?<><label className="field">Seu nome <span className="muted">(opcional)</span><input autoComplete="given-name" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Observação do pedido <span className="muted">(opcional)</span><textarea rows={3} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Algo que deseja informar à pizzaria?"/></label><fieldset className="payment-options"><legend>Forma de pagamento</legend><p className="muted small">Selecione uma opção para revisar o pedido.</p><div className="size-options">{(["Pix","Cartão","Dinheiro"] as const).map(method=><label key={method} className={"size-option "+(payment===method?"selected":"")}><input type="radio" name="payment" checked={payment===method} onChange={()=>setPayment(method)}/><span>{method}</span></label>)}</div></fieldset><button className="button primary full" disabled={!payment} onClick={()=>setReview(true)}>Revisar pedido</button><button className="button text-button full" onClick={onClose}><ArrowLeft size={16}/>Voltar ao cardápio</button></>:<>{payment&&<p className="payment-review"><strong>Preferência de pagamento:</strong> {payment}<br/><span className="muted small">A confirmar no atendimento.</span></p>}{name&&<p><strong>Nome:</strong> {name}</p>}{note&&<p className="customer-note"><strong>Observação:</strong> {note}</p>}<p className="notice"><Info size={18}/>O WhatsApp abrirá com seu pedido preenchido. Envie a mensagem e confirme valores, pagamento e entrega com o atendimento.</p><a className="button primary full" href={buildOrderWhatsAppUrl(buildWhatsAppMessage(items,name,note,payment ?? undefined))} target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>Finalizar pelo WhatsApp</a><button className="button text-button full" onClick={()=>setReview(false)}><ArrowLeft size={16}/>Editar pedido</button></>}
 </>}
 </Dialog>;
}
